---
- hosts: all
  tasks:
    - name: Install some basic packages to make the system useful
      pacman:
        name:
          - base-devel
          - bash-completion
          - bind-tools
          - curl
          - emacs
          - git
          - gnupg
          - ispell
          - mlocate
          - screen
          - source-highlight
          - stow
          - wpa_supplicant
      tags:
        - pacman
    - name: Install pyenv
      shell: curl https://pyenv.run | bash
      args:
        creates: /home/{{ ansible_user }}/.pyenv
      become_user: "{{ ansible_user }}"
      tags:
        - pyenv
    - name: Checkout .dotfiles repository
      git:
        repo: git@github.com:jsf9k/.dotfiles.git
        dest: /home/{{ ansible_user }}/.dotfiles
        accept_hostkey: yes
      become_user: "{{ ansible_user }}"
      notify:
        - Delete existing config files
        - Install dotfiles
      tags:
        - dotfiles
    - name: Ensure basic ufw service configuration
      block:
        - name: Install the ufw service
          pacman:
            name:
              - ufw
          tags:
            - pacman
        - name: Enable and start the ufw service
          systemd:
            name: ufw
            enabled: yes
            state: started
        - name: Allow incoming ssh traffic through the firewall
          ufw:
            rule: allow
            to_port: ssh
            proto: tcp
        - name: Enable firewall
          ufw:
            default: deny
            logging: 'on'
            state: enabled
      tags:
        - ufw
  handlers:
    - name: Dotfiles handlers
      block:
        # These two files are created at installation time, and they
        # will make stow fail if not removed
        - name: Delete existing config files
          file:
            path: /home/{{ ansible_user }}/{{ item }}
            state: absent
          loop:
            - .bashrc
            - .screenrc
        - name: Install dotfiles
          command: ./deploy.sh
          args:
            chdir: /home/{{ ansible_user }}/.dotfiles
          become_user: "{{ ansible_user }}"
      tags:
        - dotfiles
- hosts: basicx
  tasks:
    - name: Install packages for a basic machine with X
      pacman:
        name:
          - alsa-utils
          - chromium
          - feh
          - libu2f-host
          - ratpoison
          - rxvt-unicode
          - rxvt-unicode-terminfo
          - xdm-archlinux
          - xlockmore
          - xorg
          - xterm
      tags:
        - pacman
    - name: Install font packages
      pacman:
        name:
          - noto-fonts
          - noto-fonts-emoji
          - noto-fonts-extra
          - terminus-font
          - ttf-bitstream-vera
          - ttf-inconsolata
      tags:
        - pacman
        - fonts
    - name: Setup xdm
      block:
        - name: Replace dummy text with machine name
          replace:
            path: /etc/X11/xdm/archlinux/Xresources
            regexp: CLIENTHOST
            replace: '{{ ansible_hostname }}'
        - name: Enable and start the xdm service
          systemd:
            name: xdm-archlinux
            enabled: yes
            state: started
      tags:
        - xdm
- hosts: dev
  tasks:
    - name: Install dev packages
      pacman:
        name:
          - ansible
          - terraform
      tags:
        - pacman
- hosts: cisa
  tasks:
    - name: Setup PIV
      block:
        - name: Install PIV-related packages
          pacman:
            name:
              - ccid
              - opensc
              - pkcs11-helper
              - pcsc-tools
              - libp11
          notify:
            - Add NSS PIV module
          tags:
            - pacman
        - name: Enable and start the pcscd service
          systemd:
            name: pcscd
            enabled: yes
            state: started
      tags:
        - piv
    - name: Checkout .dotfiles_cisa repository
      git:
        repo: git@github.com:jsf9k/.dotfiles_cisa.git
        dest: /home/{{ ansible_user }}/.dotfiles_cisa
        accept_hostkey: yes
      become_user: "{{ ansible_user }}"
      notify:
        - Install CISA dotfiles
      tags:
        - dotfiles
    - name: Setup feh background
      copy:
        content: |
          #!/bin/sh
          feh --no-fehbg --bg-max --image-bg 'black' '/home/{{ ansible_user }}/images/penguin_emperor.png'
        dest: /home/{{ ansible_user }}/.fehbg
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: 0755
      tags:
        - feh
  handlers:
    - name: Install CISA dotfiles
      command: ./deploy.sh
      args:
        chdir: /home/{{ ansible_user }}/.dotfiles_cisa
      become_user: '{{ ansible_user }}'
      tags:
        - dotfiles
    - name: Add NSS PIV module
      command: modutil -force -dbdir sql:/home/{{ ansible_user }}/.pki/nssdb/ -add "PIV Module" -libfile /usr/lib/opensc-pkcs11.so
      become_user: '{{ ansible_user }}'
      tags:
        - piv
- hosts: home
  tasks:
    - name: Checkout .dotfiles_home repository
      git:
        repo: git@github.com:jsf9k/.dotfiles_home.git
        dest: /home/{{ ansible_user }}/.dotfiles_home
        accept_hostkey: yes
      become_user: "{{ ansible_user }}"
      notify:
        - Install home dotfiles
      tags:
        - dotfiles
    - name: Setup feh background
      copy:
        content: |
          #!/bin/sh
          feh --no-fehbg --bg-max --image-bg 'black' '/home/{{ ansible_user }}/images/linux_terminal_wallpaper.png'
        dest: /home/{{ ansible_user }}/.fehbg
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: 0755
      tags:
        - feh
  handlers:
    - name: Install home dotfiles
      command: ./deploy.sh
      args:
        chdir: /home/{{ ansible_user }}/.dotfiles_home
      become_user: "{{ ansible_user }}"
      tags:
        - dotfiles
