---
- hosts: all
  roles:
    - dotfiles
    - pyenv
    - ufw
  tasks:
    - name: Install some basic packages to make the system useful
      package:
        name:
          - base-devel
          - bash-completion
          - bind-tools
          - emacs
          - gnupg
          - ispell
          - mlocate
          - screen
          - source-highlight
          - wpa_supplicant
- hosts: basicx
  tasks:
    - name: Install packages for a basic machine with X
      package:
        name:
          - alsa-utils
          - chromium
          - feh
          - libu2f-host
          - ratpoison
          - rxvt-unicode
          - rxvt-unicode-terminfo
          - xdm-archlinux
          - xlockmore
          - xorg
          - xterm
    - name: Install font packages
      package:
        name:
          - noto-fonts
          - noto-fonts-emoji
          - noto-fonts-extra
          - terminus-font
          - ttf-bitstream-vera
          - ttf-inconsolata
      tags:
        - fonts
    - name: Setup xdm
      block:
        - name: Replace dummy text with machine name
          replace:
            path: /etc/X11/xdm/archlinux/Xresources
            regexp: CLIENTHOST
            replace: '{{ ansible_hostname }}'
        - name: Enable and start the xdm service
          systemd:
            name: xdm-archlinux
            enabled: yes
            state: started
      tags:
        - xdm
- hosts: dev
  tasks:
    - name: Install dev packages
      package:
        name:
          - ansible
          - terraform
- hosts: cisa
  roles:
    - dotfiles-cisa
    - piv
  tasks:
    - name: Setup feh background
      copy:
        content: |
          #!/bin/sh
          feh --no-fehbg --bg-max --image-bg 'black' '/home/{{ ansible_user }}/images/penguin_emperor.png'
        dest: /home/{{ ansible_user }}/.fehbg
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: 0755
      tags:
        - feh
- hosts: home
  roles:
    - dotfiles-home
  tasks:
    - name: Setup feh background
      copy:
        content: |
          #!/bin/sh
          feh --no-fehbg --bg-max --image-bg 'black' '/home/{{ ansible_user }}/images/linux_terminal_wallpaper.png'
        dest: /home/{{ ansible_user }}/.fehbg
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: 0755
      tags:
        - feh
