---
- hosts: all
  roles:
    - dotfiles
    - pyenv
    - ufw
  tasks:
    - name: Install some basic packages to make the system useful
      pacman:
        name:
          - base-devel
          - bash-completion
          - bind-tools
          - emacs
          - gnupg
          - ispell
          - mlocate
          - screen
          - source-highlight
          - wpa_supplicant
- hosts: basicx
  tasks:
    - name: Install packages for a basic machine with X
      pacman:
        name:
          - alsa-utils
          - chromium
          - feh
          - libu2f-host
          - ratpoison
          - rxvt-unicode
          - rxvt-unicode-terminfo
          - xdm-archlinux
          - xlockmore
          - xorg
          - xterm
      tags:
        - pacman
    - name: Install font packages
      pacman:
        name:
          - noto-fonts
          - noto-fonts-emoji
          - noto-fonts-extra
          - terminus-font
          - ttf-bitstream-vera
          - ttf-inconsolata
      tags:
        - pacman
        - fonts
    - name: Setup xdm
      block:
        - name: Replace dummy text with machine name
          replace:
            path: /etc/X11/xdm/archlinux/Xresources
            regexp: CLIENTHOST
            replace: '{{ ansible_hostname }}'
        - name: Enable and start the xdm service
          systemd:
            name: xdm-archlinux
            enabled: yes
            state: started
      tags:
        - xdm
- hosts: dev
  tasks:
    - name: Install dev packages
      pacman:
        name:
          - ansible
          - terraform
      tags:
        - pacman
- hosts: cisa
  roles:
    - piv
  tasks:
    - name: Checkout .dotfiles_cisa repository
      git:
        repo: git@github.com:jsf9k/.dotfiles_cisa.git
        dest: /home/{{ ansible_user }}/.dotfiles_cisa
        accept_hostkey: yes
      become_user: "{{ ansible_user }}"
      notify:
        - Install CISA dotfiles
      tags:
        - dotfiles
    - name: Setup feh background
      copy:
        content: |
          #!/bin/sh
          feh --no-fehbg --bg-max --image-bg 'black' '/home/{{ ansible_user }}/images/penguin_emperor.png'
        dest: /home/{{ ansible_user }}/.fehbg
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: 0755
      tags:
        - feh
  handlers:
    - name: Install CISA dotfiles
      command: ./deploy.sh
      args:
        chdir: /home/{{ ansible_user }}/.dotfiles_cisa
      become_user: '{{ ansible_user }}'
      tags:
        - dotfiles
- hosts: home
  tasks:
    - name: Checkout .dotfiles_home repository
      git:
        repo: git@github.com:jsf9k/.dotfiles_home.git
        dest: /home/{{ ansible_user }}/.dotfiles_home
        accept_hostkey: yes
      become_user: "{{ ansible_user }}"
      notify:
        - Install home dotfiles
      tags:
        - dotfiles
    - name: Setup feh background
      copy:
        content: |
          #!/bin/sh
          feh --no-fehbg --bg-max --image-bg 'black' '/home/{{ ansible_user }}/images/linux_terminal_wallpaper.png'
        dest: /home/{{ ansible_user }}/.fehbg
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: 0755
      tags:
        - feh
  handlers:
    - name: Install home dotfiles
      command: ./deploy.sh
      args:
        chdir: /home/{{ ansible_user }}/.dotfiles_home
      become_user: "{{ ansible_user }}"
      tags:
        - dotfiles
