---
- hosts: all
  tasks:
    - name: Group hosts by OS family
      group_by:
        key: os_family_{{ ansible_facts['os_family'] }}
- hosts: os_family_Debian
  tasks:
    - name: Install aptitude
      package:
        name:
          - aptitude
- hosts: all
  roles:
    - dotfiles
    - pyenv
    - ufw
    - wireless
- hosts: afp
  roles:
    - afp
- hosts: basicx
  roles:
    - audio
    - fonts
    - x-basic
    - xdm
- hosts: dev
  roles:
    - dev
- hosts: hfs
  roles:
    - hfs
- hosts: cisa
  roles:
    - dotfiles-cisa
    - piv
- hosts: cisa:&basicx
  roles:
    - feh-cisa
- hosts: home
  roles:
    - dotfiles-home
- hosts: home:&basicx
  roles:
    - feh-home
