---
- hosts: all
  tasks:
    - name: Group hosts by OS family
      group_by:
        key: os_family_{{ ansible_facts['os_family'] }}
  roles:
    - dotfiles
    - pyenv
    - ufw
    - wireless
- hosts: os_family_Debian
  tasks:
    - name: Install aptitude
      package:
        name:
          - aptitude
- hosts: basicx
  roles:
    - audio
    - fonts
    - x-basic
    - xdm
- hosts: dev
  roles:
    - dev
- hosts: cisa
  roles:
    - dotfiles-cisa
    - feh-cisa
    - piv
- hosts: home
  roles:
    - dotfiles-home
    - feh-home
