---
- hosts: all
  roles:
    - dotfiles
    - pyenv
    - ufw
    - wireless
- hosts: basicx
  roles:
    - audio
    - fonts
    - x-basic
    - xdm
- hosts: dev
  roles:
    - dev
- hosts: cisa
  roles:
    - dotfiles-cisa
    - feh-cisa
    - piv
- hosts: home
  roles:
    - dotfiles-home
    - feh-home
