---
- name: Ensure basic ufw service configuration
  block:
    - name: Install the ufw service
      pacman:
        name:
          - ufw
    - name: Enable and start the ufw service
      systemd:
        name: ufw
        enabled: yes
        state: started
    - name: Allow incoming ssh traffic through the firewall
      ufw:
        rule: allow
        to_port: ssh
        proto: tcp
    - name: Enable firewall
      ufw:
        default: deny
        logging: 'on'
        state: enabled
  tags:
    - ufw
